title: Irched chafaa # your name (or website title) here
logo: "/images/profile_IC.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
  PhD. in Telecommunication, Paris-Saclay University, France.
  
  <br><br>
  IBM Data Science professional certificate.
  <br><br>
  
  <a href="https://www.linkedin.com/in/ic33/">View My LinkedIn Profile</a> 

  <a href="https://scholar.google.com/citations?user=Mbo9cWUAAAAJ&hl=en">List of Publications</a> 
  
  <br>
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
